version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    open-pull-requests-limit: 10
